name: NFD

plugins:
  - name: hardhat
  - name: solidity
    version: 0.8.2

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 5.0.2
  - name: Tableland
    github: tablelandnetwork/evm-tableland
    version: 6.3.0
  - name: erc721a-upgradeable
    github: chiru-labs/ERC721A-Upgradeable
    version: 4.2.3

networks:
  custom:
    - name: tableland
      ecosystem: ethereum
      base_ecosystem_plugin: ethereum
      chain_id: 31337
      default_provider: node
    - name: mainnet
      ecosystem: filecoin
      base_ecosystem_plugin: ethereum
      chain_id: 314
      default_provider: node
    - name: calibration
      ecosystem: filecoin
      base_ecosystem_plugin: ethereum
      chain_id: 314159
      default_provider: node

node:
  ethererum:
    tableland:
      uri: http://127.0.0.1:8545/
  filecoin:
    filecoin:
      uri: https://api.node.glif.io/rpc/v1
    filecoin-calibration:
      uri: https://api.calibration.node.glif.io/rpc/v1

ethereum:
  default_network: tableland
  tableland:
    default_transaction_type: 0



